site_name: laravel-repository-release
site_url: https://matmper.github.io/laravel-repository-release
nav:
  - Home: index.md
  - Configuration: configuration.md
  - Quick Start: quick-start.md
  - Usage: usage.md
theme: readthedocs
