site_name: laravel-repository-release
site_url: https://laravel-repository-release.matheusp.com.br
nav:
  - Home: index.md
  - Configuration: configuration.md
  - Quick Start: quick-start.md
  - Usage: usage.md
theme: readthedocs