name: "Tests Actions"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Cache composer dependencies
      uses: actions/cache@v2
      with:
        path: vendor
        key: composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          composer-

    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2

    - name: Install composer dependencies
      run: |
        composer install --dev --prefer-dist --no-progress --no-interaction

    - name: Run PHP Code Sniffer suit
      run: composer phpcs

    - name: Run PHP Stan suit
      run: composer phpstan

    - name: Run PHP Unit Tests suite
      run: composer tests